import { useEffect, useState } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { ArrowLeft, Play, Trash2, Save } from "lucide-react";
import * as api from "../api";
import { useStore } from "../store";
import type { Session, Task } from "../api/types";
import { AgentBadge, PriorityBadge, TaskStatusBadge, SessionStatusBadge, SessionKindBadge } from "../components/Badges";
import { formatCost, formatRelative } from "../lib/format";

export function TaskDetailView() {
  const { id = "" } = useParams();
  const navigate = useNavigate();
  const projects = useStore((s) => s.projects);
  const refreshTasks = useStore((s) => s.refreshTasks);
  const [task, setTask] = useState<Task | null>(null);
  const [sessions, setSessions] = useState<Session[]>([]);
  const [desc, setDesc] = useState("");
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    let active = true;
    const loadTask = () => api.getTask(id).then((t) => { if (active) { setTask(t); setDesc(t.description); } }).catch(() => {});
    const loadSessions = () => api.listSessions({ taskId: id }).then((s) => active && setSessions(s)).catch(() => {});
    loadTask();
    loadSessions();
    const unlisten = api.onOrchestratorEvent((e) => {
      if (e.type === "taskUpdated" && e.task.id === id) setTask(e.task);
      if (e.type === "sessionUpdated") loadSessions();
    });
    return () => { active = false; unlisten.then((u) => u()); };
  }, [id]);

  if (!task) return <div className="p-6 text-sm text-neutral-500">Loading task…</div>;

  const project = projects.find((p) => p.id === task.projectId);

  const save = async () => {
    await api.updateTask({ ...task, description: desc });
    setSaved(true);
    setTimeout(() => setSaved(false), 1500);
  };
  const runNow = async () => { await api.runTaskNow(task.id); };
  const del = async () => { await api.deleteTask(task.id); await refreshTasks(); navigate("/tasks"); };

  return (
    <div className="p-6">
      <button className="mb-3 flex items-center gap-1 text-xs text-neutral-400 hover:text-neutral-200" onClick={() => navigate(-1)}>
        <ArrowLeft size={14} /> Back
      </button>

      <div className="mb-4 flex items-start justify-between gap-4">
        <div className="min-w-0">
          <h1 className="truncate text-lg font-semibold text-neutral-100">{task.title}</h1>
          {project && (
            <Link to={`/projects/${project.id}`} className="text-xs text-indigo-300 hover:underline">{project.name}</Link>
          )}
        </div>
        <div className="flex gap-2">
          <button className="btn" onClick={runNow}><Play size={14} /> Run now</button>
          <button className="btn btn-danger" onClick={del}><Trash2 size={14} /></button>
        </div>
      </div>

      <div className="mb-4 flex flex-wrap items-center gap-2">
        <TaskStatusBadge status={task.status} />
        <PriorityBadge priority={task.priority} />
        <AgentBadge agent={task.agent} />
        {task.autoGenerated && <span className="chip border-blue-500/40 bg-blue-500/10 text-blue-300">auto-generated</span>}
        <span className="text-xs text-neutral-500">attempts {task.attempts}/{task.maxAttempts}</span>
        {task.tags.map((t) => (
          <span key={t} className="chip border-[var(--color-border)] text-neutral-400">{t}</span>
        ))}
      </div>

      <div className="card mb-6 p-4">
        <label className="mb-1 block text-xs text-neutral-400">Instructions / acceptance criteria</label>
        <textarea
          className="input min-h-[180px] resize-y font-mono text-xs"
          value={desc}
          onChange={(e) => setDesc(e.target.value)}
        />
        <div className="mt-2 flex items-center gap-2">
          <button className="btn btn-primary" onClick={save} disabled={desc === task.description}>
            <Save size={14} /> Save
          </button>
          {saved && <span className="text-xs text-emerald-400">Saved</span>}
        </div>
      </div>

      <h3 className="mb-2 text-sm font-semibold text-neutral-200">Sessions ({sessions.length})</h3>
      <div className="flex flex-col gap-1.5">
        {sessions.length === 0 && <div className="text-sm text-neutral-500">No sessions have run for this task yet.</div>}
        {sessions.map((s) => (
          <Link
            key={s.id}
            to={`/sessions/${s.id}`}
            className="flex items-center gap-3 rounded-md border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-sm hover:border-indigo-500/40"
          >
            <SessionKindBadge kind={s.kind} />
            <SessionStatusBadge status={s.status} />
            <span className="min-w-0 flex-1 truncate text-neutral-400">{s.resultText?.slice(0, 80) ?? s.error ?? "—"}</span>
            <span className="text-xs text-neutral-500">{formatCost(s.usage.totalCostUsd)}</span>
            <span className="text-xs text-neutral-600">{formatRelative(s.createdAt)}</span>
          </Link>
        ))}
      </div>
    </div>
  );
}
