// Types mirroring `orchestrator-core` model structs (serialized as camelCase).

export type AgentKind = "claude" | "gemini" | "codex";

export type TaskStatus =
  | "pending"
  | "queued"
  | "running"
  | "needs_review"
  | "completed"
  | "failed"
  | "cancelled"
  | "blocked";

export type SessionKind = "task" | "roadmap" | "verify";

export type SessionStatus =
  | "pending"
  | "running"
  | "completed"
  | "failed"
  | "cancelled"
  | "timed_out";

export type PermissionMode =
  | "default"
  | "accept-edits"
  | "plan"
  | "bypass-permissions";

export interface Project {
  id: string;
  name: string;
  path: string;
  description: string | null;
  enabled: boolean;
  defaultAgent: AgentKind;
  maxConcurrent: number | null;
  roadmapEnabled: boolean;
  verifyEnabled: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Task {
  id: string;
  projectId: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: number;
  agent: AgentKind;
  parentId: string | null;
  dependsOn: string[];
  attempts: number;
  maxAttempts: number;
  tags: string[];
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheCreationTokens: number;
  totalCostUsd: number;
  numTurns: number;
}

export interface Session {
  id: string;
  taskId: string | null;
  projectId: string;
  agent: AgentKind;
  kind: SessionKind;
  status: SessionStatus;
  agentSessionId: string | null;
  model: string | null;
  prompt: string;
  resultText: string | null;
  error: string | null;
  exitCode: number | null;
  usage: TokenUsage;
  startedAt: string | null;
  endedAt: string | null;
  createdAt: string;
}

export interface SessionEvent {
  id: number;
  sessionId: string;
  kind: string;
  text: string | null;
  data: unknown | null;
  createdAt: string;
}

export interface AgentLimits {
  costLimitUsd: number | null;
  tokenLimit: number | null;
}

export interface AgentUsage {
  agent: AgentKind;
  available: boolean;
  window: TokenUsage;
  total: TokenUsage;
  activeSessions: number;
  limits: AgentLimits;
  windowStartedAt: string;
  windowHours: number;
}

export interface OrchestratorStatus {
  running: boolean;
  activeSessions: number;
  maxConcurrent: number;
  pendingTasks: number;
  projects: number;
  agents: AgentUsage[];
}

export interface TimelineItem {
  sessionId: string;
  taskId: string | null;
  taskTitle: string | null;
  projectId: string;
  projectName: string;
  agent: AgentKind;
  kind: SessionKind;
  status: SessionStatus;
  startedAt: string | null;
  endedAt: string | null;
  costUsd: number;
}

export interface AgentConfig {
  binary: string | null;
  model: string | null;
  extraArgs: string[];
  limits: AgentLimits;
  windowHours: number;
  enabled: boolean;
}

export interface Settings {
  running: boolean;
  maxConcurrent: number;
  tickIntervalSecs: number;
  defaultAgent: AgentKind;
  permissionMode: PermissionMode;
  sessionTimeoutSecs: number;
  roadmapEnabled: boolean;
  verifyEnabled: boolean;
  agents: Record<string, AgentConfig>;
}

// Inputs
export interface AddProjectInput {
  path: string;
  name?: string | null;
  description?: string | null;
  scaffold?: boolean;
}

export interface CreateTaskInput {
  projectId: string;
  title: string;
  description?: string;
  priority?: number | null;
  agent?: AgentKind | null;
  dependsOn?: string[];
  tags?: string[];
  maxAttempts?: number | null;
}

// Engine events (payload of the `orchestrator://event` channel).
export type OrchestratorEvent =
  | {
      type: "sessionEvent";
      sessionId: string;
      projectId: string;
      taskId: string | null;
      event: SessionEvent;
    }
  | { type: "sessionUpdated"; session: Session }
  | { type: "taskUpdated"; task: Task }
  | { type: "statusChanged" }
  | { type: "usageUpdated" }
  | { type: "log"; level: string; message: string };
