// Types mirroring `orchestrator-core` model structs (serialized as camelCase).

export type AgentKind = "claude" | "gemini" | "codex";

export type TaskStatus =
  | "pending"
  | "queued"
  | "running"
  | "needs_review"
  | "completed"
  | "failed"
  | "cancelled"
  | "blocked";

export type SessionKind = "task" | "roadmap" | "verify";

export type SessionStatus =
  | "pending"
  | "running"
  | "completed"
  | "failed"
  | "cancelled"
  | "timed_out";

export type PermissionMode =
  | "default"
  | "accept-edits"
  | "plan"
  | "bypass-permissions";

export interface Project {
  id: string;
  name: string;
  path: string;
  description: string | null;
  enabled: boolean;
  defaultAgent: AgentKind;
  allowedAgents: AgentKind[];
  maxConcurrent: number | null;
  roadmapEnabled: boolean;
  verifyEnabled: boolean;
  defaultMaxAttempts: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface Task {
  id: string;
  projectId: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: number;
  agent: AgentKind;
  autoAgent: boolean;
  model: string | null;
  parentId: string | null;
  dependsOn: string[];
  attempts: number;
  maxAttempts: number;
  tags: string[];
  autoGenerated: boolean;
  retryAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheCreationTokens: number;
  totalCostUsd: number;
  numTurns: number;
}

export interface Session {
  id: string;
  taskId: string | null;
  projectId: string;
  agent: AgentKind;
  kind: SessionKind;
  status: SessionStatus;
  agentSessionId: string | null;
  model: string | null;
  prompt: string;
  resultText: string | null;
  error: string | null;
  exitCode: number | null;
  usage: TokenUsage;
  branch: string | null;
  prUrl: string | null;
  startedAt: string | null;
  endedAt: string | null;
  createdAt: string;
}

export interface SessionEvent {
  id: number;
  sessionId: string;
  kind: string;
  text: string | null;
  data: unknown | null;
  createdAt: string;
}

export interface AgentLimits {
  sessionCostUsd: number | null;
  weeklyCostUsd: number | null;
  sessionTokenLimit: number | null;
  weeklyTokenLimit: number | null;
}

export interface WindowUsage {
  usage: TokenUsage;
  windowHours: number;
  windowStartedAt: string | null;
  costLimitUsd: number | null;
  tokenLimit: number | null;
  costPct: number | null;
  tokenPct: number | null;
}

export interface AgentUsage {
  agent: AgentKind;
  available: boolean;
  activeSessions: number;
  session: WindowUsage;
  weekly: WindowUsage;
  total: TokenUsage;
}

export interface UsagePoint {
  period: string;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheCreationTokens: number;
  totalTokens: number;
  costUsd: number;
  numTurns: number;
  sessions: number;
}

export interface OrchestratorStatus {
  running: boolean;
  draining: boolean;
  activeSessions: number;
  maxConcurrent: number;
  pendingTasks: number;
  projects: number;
  agents: AgentUsage[];
}

export interface TimelineItem {
  sessionId: string;
  taskId: string | null;
  taskTitle: string | null;
  projectId: string;
  projectName: string;
  agent: AgentKind;
  kind: SessionKind;
  status: SessionStatus;
  startedAt: string | null;
  endedAt: string | null;
  costUsd: number;
}

export interface AgentConfig {
  binary: string | null;
  model: string | null;
  extraArgs: string[];
  limits: AgentLimits;
  sessionWindowHours: number;
  weeklyWindowHours: number;
  enabled: boolean;
}

export interface Settings {
  running: boolean;
  maxConcurrent: number;
  tickIntervalSecs: number;
  defaultAgent: AgentKind;
  permissionMode: PermissionMode;
  sessionTimeoutSecs: number;
  roadmapEnabled: boolean;
  verifyEnabled: boolean;
  balanceAgents: boolean;
  liveStreaming: boolean;
  notificationsEnabled: boolean;
  isolateWorktrees: boolean;
  autoCommit: boolean;
  autoPr: boolean;
  scheduleRefreshSecs: number;
  retryEnabled: boolean;
  retryBaseSecs: number;
  retryMaxSecs: number;
  webhooks: WebhookConfig[];
  agents: Record<string, AgentConfig>;
}

export interface AgentStat {
  agent: AgentKind;
  sessions: number;
  completed: number;
  failed: number;
  successRate: number;
  avgCostUsd: number;
  totalCostUsd: number;
  avgDurationSecs: number;
}

export interface ProjectMemory {
  context: string | null;
  lessons: string | null;
}

export interface DiffFile {
  path: string;
  additions: number;
  deletions: number;
  status: string;
}

export interface SessionDiff {
  available: boolean;
  branch: string | null;
  base: string | null;
  files: DiffFile[];
  additions: number;
  deletions: number;
  patch: string;
  truncated: boolean;
}

export interface AgentHealth {
  agent: AgentKind;
  binary: string;
  available: boolean;
  version: string | null;
}

export interface BranchInfo {
  name: string;
  merged: boolean;
  active: boolean;
  conflicted: boolean | null;
  behind: number;
}

export interface RebaseResult {
  status: string;
  detail: string;
}

export interface PullRequest {
  number: number;
  title: string;
  url: string;
  state: string;
  draft: boolean;
  branch: string;
  ci: string;
  reviewDecision: string | null;
  mergeable: string | null;
}

export interface WebhookConfig {
  id: string;
  name: string;
  url: string;
  kind: string;
  enabled: boolean;
  onTaskComplete: boolean;
  onTaskFail: boolean;
  projectIds: string[];
}

export interface ActivityEntry {
  id: number;
  kind: string;
  level: string;
  message: string;
  projectId: string | null;
  projectName: string | null;
  taskId: string | null;
  sessionId: string | null;
  createdAt: string;
}

export interface ScheduledTask {
  id: string;
  projectId: string;
  path: string;
  relPath: string;
  title: string;
  schedule: string;
  scheduleKind: string;
  scheduleDesc: string;
  agent: AgentKind | null;
  model: string | null;
  priority: number;
  enabled: boolean;
  valid: boolean;
  error: string | null;
  body: string;
  lastRun: string | null;
  nextRun: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface GitStatus {
  available: boolean;
  branch: string | null;
  dirty: boolean;
  ahead: number;
  behind: number;
  lastCommit: string | null;
  lastSubject: string | null;
}

export interface UpcomingTask {
  scheduledId: string;
  projectId: string;
  projectName: string;
  title: string;
  agent: AgentKind | null;
  priority: number;
  scheduleDesc: string;
  runAt: string;
}

// Inputs
export interface AddProjectInput {
  path: string;
  name?: string | null;
  description?: string | null;
  scaffold?: boolean;
}

export interface CreateTaskInput {
  projectId: string;
  title: string;
  description?: string;
  priority?: number | null;
  agent?: AgentKind | null;
  model?: string | null;
  dependsOn?: string[];
  tags?: string[];
  maxAttempts?: number | null;
}

// Engine events (payload of the `orchestrator://event` channel).
export type OrchestratorEvent =
  | {
      type: "sessionEvent";
      sessionId: string;
      projectId: string;
      taskId: string | null;
      event: SessionEvent;
    }
  | {
      type: "sessionDelta";
      sessionId: string;
      kind: string;
      text: string;
    }
  | { type: "sessionUpdated"; session: Session }
  | { type: "taskUpdated"; task: Task }
  | { type: "statusChanged" }
  | { type: "scheduledChanged" }
  | { type: "usageUpdated" }
  | { type: "activity"; entry: ActivityEntry }
  | { type: "log"; level: string; message: string };
