import { useNavigate } from "react-router-dom";
import { Play, Trash2, Sparkles } from "lucide-react";
import * as api from "../api";
import { useStore } from "../store";
import type { Task } from "../api/types";
import { AgentBadge, PriorityBadge, TaskStatusBadge } from "./Badges";
import { formatRelative } from "../lib/format";

export function TaskTable({ tasks, showProject = false }: { tasks: Task[]; showProject?: boolean }) {
  const navigate = useNavigate();
  const projects = useStore((s) => s.projects);
  const refreshTasks = useStore((s) => s.refreshTasks);

  const projectName = (id: string) => projects.find((p) => p.id === id)?.name ?? id.slice(0, 6);

  const runNow = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    await api.runTaskNow(id);
  };
  const del = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    await api.deleteTask(id);
    await refreshTasks();
  };

  if (tasks.length === 0) {
    return <div className="px-4 py-8 text-center text-sm text-neutral-500">No tasks.</div>;
  }

  return (
    <div className="overflow-hidden rounded-lg border border-[var(--color-border)]">
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b border-[var(--color-border)] bg-[var(--color-surface-2)] text-left text-xs text-neutral-500">
            <th className="px-3 py-2 font-medium">Task</th>
            {showProject && <th className="px-3 py-2 font-medium">Project</th>}
            <th className="px-3 py-2 font-medium">Status</th>
            <th className="px-3 py-2 font-medium">Priority</th>
            <th className="px-3 py-2 font-medium">Agent</th>
            <th className="px-3 py-2 font-medium">Updated</th>
            <th className="px-3 py-2" />
          </tr>
        </thead>
        <tbody>
          {tasks.map((t) => (
            <tr
              key={t.id}
              className="cursor-pointer border-b border-[var(--color-border)] last:border-0 hover:bg-[var(--color-surface-2)]"
              onClick={() => navigate(`/tasks/${t.id}`)}
            >
              <td className="max-w-[320px] px-3 py-2.5">
                <div className="flex items-center gap-1.5 truncate text-neutral-100">
                  {t.autoGenerated && <Sparkles size={12} className="shrink-0 text-blue-400" />}
                  <span className="truncate">{t.title}</span>
                </div>
                {t.attempts > 0 && (
                  <span className="text-[11px] text-neutral-500">
                    attempt {t.attempts}/{t.maxAttempts}
                  </span>
                )}
              </td>
              {showProject && <td className="px-3 py-2.5 text-neutral-400">{projectName(t.projectId)}</td>}
              <td className="px-3 py-2.5"><TaskStatusBadge status={t.status} /></td>
              <td className="px-3 py-2.5"><PriorityBadge priority={t.priority} /></td>
              <td className="px-3 py-2.5"><AgentBadge agent={t.agent} /></td>
              <td className="px-3 py-2.5 text-xs text-neutral-500">{formatRelative(t.updatedAt)}</td>
              <td className="px-3 py-2.5">
                <div className="flex justify-end gap-1">
                  <button className="btn !px-2 !py-1" title="Run now" onClick={(e) => runNow(e, t.id)}>
                    <Play size={13} />
                  </button>
                  <button className="btn btn-danger !px-2 !py-1" title="Delete" onClick={(e) => del(e, t.id)}>
                    <Trash2 size={13} />
                  </button>
                </div>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
