// Mock Tauri IPC injected before the app loads, so the real UI renders with
// representative data in a plain browser (no Tauri host).
window.__SHOT_MOCK__ = (() => {
  const now = Date.now();
  const iso = (msFromNow) => new Date(now + msFromNow).toISOString();

  const projects = [
    { id: "p1", name: "claude-orchestrator", path: "/home/user/claude-orchestrator", description: "Self-hosted orchestrator", enabled: true, defaultAgent: "claude", allowedAgents: ["claude", "gemini", "codex"], maxConcurrent: null, roadmapEnabled: true, verifyEnabled: true, createdAt: iso(-8.64e7), updatedAt: iso(-3600e3) },
    { id: "p2", name: "web-dashboard", path: "/home/user/projects/web-dashboard", description: null, enabled: true, defaultAgent: "claude", allowedAgents: ["claude", "gemini"], maxConcurrent: 2, roadmapEnabled: true, verifyEnabled: true, createdAt: iso(-1.7e8), updatedAt: iso(-7200e3) },
    { id: "p3", name: "api-gateway", path: "/home/user/projects/api-gateway", description: null, enabled: false, defaultAgent: "claude", allowedAgents: ["claude"], maxConcurrent: null, roadmapEnabled: false, verifyEnabled: true, createdAt: iso(-2.6e8), updatedAt: iso(-2.6e8) },
  ];

  const mkTask = (id, projectId, title, status, priority, agent, opts = {}) => ({
    id, projectId, title, description: "Implement the feature end to end with tests and ensure the build passes.", status, priority, agent, autoAgent: opts.autoAgent ?? false, model: opts.model ?? null, parentId: null, dependsOn: [], attempts: opts.attempts ?? 0, maxAttempts: 3, tags: opts.tags ?? [], autoGenerated: opts.autoGenerated ?? false, createdAt: iso(-3600e3), updatedAt: iso(-600e3),
  });
  const tasks = [
    mkTask("t1", "p1", "Add partial-message streaming to the session view", "running", 100, "claude"),
    mkTask("t2", "p1", "Persist usage windows across restarts", "pending", 50, "claude", { autoAgent: true }),
    mkTask("t3", "p1", "Write end-to-end test for the roadmap loop", "needs_review", 50, "gemini", { attempts: 1 }),
    mkTask("t4", "p2", "Dark-mode polish for the settings panel", "completed", 50, "claude"),
    mkTask("t5", "p2", "Fix flaky pagination test", "failed", 100, "codex", { attempts: 3 }),
    mkTask("t6", "p1", "Generate API docs from the command surface", "pending", 0, "claude", { autoGenerated: true, tags: ["docs"] }),
    mkTask("t7", "p2", "Add keyboard shortcuts for navigation", "pending", 50, "gemini", { autoAgent: true }),
    mkTask("t8", "p1", "Audit dependencies for vulnerabilities", "queued", 200, "claude", { tags: ["scheduled"] }),
  ];

  const usage = (i, o, cr, cost, turns) => ({ inputTokens: i, outputTokens: o, cacheReadTokens: cr, cacheCreationTokens: 0, totalCostUsd: cost, numTurns: turns });
  const win = (u, hours, costLimit) => ({
    usage: u, windowHours: hours, windowStartedAt: iso(-hours * 3.6e6),
    costLimitUsd: costLimit, tokenLimit: null,
    costPct: costLimit ? u.totalCostUsd / costLimit : null, tokenPct: null,
  });
  const status = {
    running: true, draining: false, activeSessions: 2, maxConcurrent: 3, pendingTasks: 5, projects: 3,
    agents: [
      { agent: "claude", available: true, activeSessions: 1,
        session: win(usage(820000, 240000, 1900000, 4.21, 18), 5, 8), weekly: win(usage(5200000, 1400000, 9800000, 22.4, 96), 168, 50), total: usage(0,0,0,52.4,0) },
      { agent: "gemini", available: true, activeSessions: 1,
        session: win(usage(140000, 60000, 0, 0.83, 6), 5, null), weekly: win(usage(900000, 320000, 0, 4.6, 28), 168, null), total: usage(0,0,0,6.1,0) },
      { agent: "codex", available: false, activeSessions: 0,
        session: win(usage(0,0,0,0,0), 5, null), weekly: win(usage(0,0,0,0,0), 168, null), total: usage(0,0,0,0,0) },
    ],
  };

  // Usage time-series for the dashboard.
  const usagePoint = (period, base) => ({
    period, inputTokens: base * 8000, outputTokens: base * 2500, cacheReadTokens: base * 14000,
    cacheCreationTokens: base * 400, totalTokens: base * 24900, costUsd: base * 0.42, numTurns: base * 6, sessions: base,
  });
  const daySeries = Array.from({ length: 14 }, (_, i) => {
    const d = new Date(now - (13 - i) * 8.64e7);
    const period = d.toISOString().slice(0, 10);
    return usagePoint(period, 2 + Math.round(6 * Math.abs(Math.sin(i * 1.1))));
  });
  const monthSeries = ["2026-01","2026-02","2026-03","2026-04","2026-05","2026-06"].map((p, i) => usagePoint(p, 40 + i * 14));
  const yearSeries = ["2024","2025","2026"].map((p, i) => usagePoint(p, 180 + i * 120));

  const timeline = [
    { sessionId: "s1", taskId: "t1", taskTitle: tasks[0].title, projectId: "p1", projectName: "claude-orchestrator", agent: "claude", kind: "task", status: "running", startedAt: iso(-180e3), endedAt: null, costUsd: 0.42 },
    { sessionId: "s9", taskId: "t7", taskTitle: tasks[6].title, projectId: "p2", projectName: "web-dashboard", agent: "gemini", kind: "task", status: "running", startedAt: iso(-60e3), endedAt: null, costUsd: 0.11 },
    { sessionId: "s2", taskId: "t4", taskTitle: tasks[3].title, projectId: "p2", projectName: "web-dashboard", agent: "claude", kind: "task", status: "completed", startedAt: iso(-1800e3), endedAt: iso(-1500e3), costUsd: 0.88 },
    { sessionId: "s3", taskId: null, taskTitle: null, projectId: "p1", projectName: "claude-orchestrator", agent: "claude", kind: "roadmap", status: "completed", startedAt: iso(-2400e3), endedAt: iso(-2300e3), costUsd: 0.21 },
    { sessionId: "s4", taskId: "t3", taskTitle: tasks[2].title, projectId: "p1", projectName: "claude-orchestrator", agent: "gemini", kind: "verify", status: "completed", startedAt: iso(-3000e3), endedAt: iso(-2900e3), costUsd: 0.05 },
    { sessionId: "s5", taskId: "t5", taskTitle: tasks[4].title, projectId: "p2", projectName: "web-dashboard", agent: "codex", kind: "task", status: "failed", startedAt: iso(-4000e3), endedAt: iso(-3800e3), costUsd: 0.33 },
  ];

  const scheduled = [
    { id: "sc1", projectId: "p1", path: "/home/user/claude-orchestrator/.orchestrator/scheduled/dep-audit.md", relPath: ".orchestrator/scheduled/dep-audit.md", title: "Weekly dependency audit", schedule: "0 9 * * 1", scheduleKind: "cron", scheduleDesc: "cron: 0 9 * * 1", agent: "claude", model: "opus", priority: 50, enabled: true, valid: true, error: null, body: "Audit dependencies...", lastRun: iso(-6.04e8), nextRun: iso(1.2e8), createdAt: iso(-6e8), updatedAt: iso(-6e8) },
    { id: "sc2", projectId: "p2", path: "/home/user/projects/web-dashboard/.orchestrator/scheduled/lint.md", relPath: ".orchestrator/scheduled/lint.md", title: "Nightly lint sweep", schedule: "6h", scheduleKind: "interval", scheduleDesc: "every 6h", agent: null, model: null, priority: 50, enabled: true, valid: true, error: null, body: "Run linters...", lastRun: iso(-2.1e7), nextRun: iso(1.4e7), createdAt: iso(-3e8), updatedAt: iso(-3e8) },
    { id: "sc3", projectId: "p1", path: "/home/user/claude-orchestrator/.orchestrator/scheduled/broken.md", relPath: ".orchestrator/scheduled/broken.md", title: "broken", schedule: "", scheduleKind: "", scheduleDesc: "", agent: null, model: null, priority: 50, enabled: true, valid: false, error: "missing `schedule` (cron) or `every` (interval) in front matter", body: "", lastRun: null, nextRun: null, createdAt: iso(-1e8), updatedAt: iso(-1e8) },
  ];

  const upcoming = [
    { scheduledId: "sc2", projectId: "p2", projectName: "web-dashboard", title: "Nightly lint sweep", agent: null, priority: 50, scheduleDesc: "every 6h", runAt: iso(1.4e7) },
    { scheduledId: "sc2", projectId: "p2", projectName: "web-dashboard", title: "Nightly lint sweep", agent: null, priority: 50, scheduleDesc: "every 6h", runAt: iso(1.4e7 + 2.16e7) },
    { scheduledId: "sc1", projectId: "p1", projectName: "claude-orchestrator", title: "Weekly dependency audit", agent: "claude", priority: 50, scheduleDesc: "cron: 0 9 * * 1", runAt: iso(1.2e8) },
    { scheduledId: "sc2", projectId: "p2", projectName: "web-dashboard", title: "Nightly lint sweep", agent: null, priority: 50, scheduleDesc: "every 6h", runAt: iso(1.4e7 + 4.32e7) },
    { scheduledId: "sc1", projectId: "p1", projectName: "claude-orchestrator", title: "Weekly dependency audit", agent: "claude", priority: 50, scheduleDesc: "cron: 0 9 * * 1", runAt: iso(1.2e8 + 6.04e8) },
  ];

  const settings = {
    running: true, maxConcurrent: 3, tickIntervalSecs: 10, defaultAgent: "claude", permissionMode: "bypass-permissions", sessionTimeoutSecs: 1800, roadmapEnabled: true, verifyEnabled: true, balanceAgents: true, liveStreaming: true, notificationsEnabled: true, isolateWorktrees: true, autoCommit: true, autoPr: false, scheduleRefreshSecs: 300,
    webhooks: [{ id: "wh1", name: "Team Slack", url: "https://hooks.slack.com/services/T00/B00/xyz", kind: "slack", enabled: true, onTaskComplete: true, onTaskFail: true }],
    agents: {
      claude: { binary: null, model: null, extraArgs: [], limits: { costLimitUsd: 25, tokenLimit: null }, windowHours: 5, enabled: true },
      gemini: { binary: null, model: null, extraArgs: [], limits: { costLimitUsd: null, tokenLimit: null }, windowHours: 5, enabled: true },
      codex: { binary: null, model: null, extraArgs: [], limits: { costLimitUsd: null, tokenLimit: null }, windowHours: 5, enabled: true },
    },
  };

  const session = { id: "s1", taskId: "t1", projectId: "p1", agent: "claude", kind: "task", status: "running", agentSessionId: "abc-123", model: "claude-opus-4", prompt: "# Task: Add partial-message streaming to the session view\n\nImplement incremental token rendering...", resultText: null, error: null, exitCode: null, usage: usage(82000, 14000, 190000, 0.42, 4), branch: "orchestrator/add-streaming-1a2b3c4d", prUrl: null, startedAt: iso(-180e3), endedAt: null, createdAt: iso(-200e3) };
  const sessionEvents = [
    { id: 1, sessionId: "s1", kind: "init", text: "session initialized (claude-opus-4)", data: null, createdAt: iso(-180e3) },
    { id: 2, sessionId: "s1", kind: "assistant", text: "I'll start by locating the session view component and the event stream handler.", data: null, createdAt: iso(-175e3) },
    { id: 3, sessionId: "s1", kind: "tool_use", text: "Grep", data: { name: "Grep", input: { pattern: "onOrchestratorEvent", glob: "**/*.tsx" } }, createdAt: iso(-170e3) },
    { id: 4, sessionId: "s1", kind: "tool_result", text: "src/views/SessionDetailView.tsx\nsrc/store/index.ts", data: { isError: false }, createdAt: iso(-168e3) },
    { id: 5, sessionId: "s1", kind: "thinking", text: "The partial messages arrive as stream_event deltas; I should accumulate them per message id.", data: null, createdAt: iso(-160e3) },
    { id: 6, sessionId: "s1", kind: "assistant", text: "I'll add a partials buffer keyed by message id and flush on message stop.", data: null, createdAt: iso(-150e3) },
  ];

  return { projects, tasks, status, timeline, scheduled, upcoming, settings, session, sessionEvents, daySeries, monthSeries, yearSeries };
})();

window.__TAURI_INTERNALS__ = {
  transformCallback(cb) { const id = Math.floor(Math.random() * 1e9); window["_cb_" + id] = cb; return id; },
  metadata: { currentWindow: { label: "main" }, currentWebview: { label: "main" } },
  invoke(cmd, args) {
    const m = window.__SHOT_MOCK__;
    const find = (arr, id) => arr.find((x) => x.id === id);
    switch (cmd) {
      case "get_status": return Promise.resolve(m.status);
      case "list_projects": return Promise.resolve(m.projects);
      case "get_project": return Promise.resolve(find(m.projects, args.id));
      case "list_tasks": return Promise.resolve(args.projectId ? m.tasks.filter((t) => t.projectId === args.projectId) : m.tasks);
      case "get_task": return Promise.resolve(find(m.tasks, args.id));
      case "get_timeline": return Promise.resolve(m.timeline);
      case "list_scheduled": return Promise.resolve(args.projectId ? m.scheduled.filter((s) => s.projectId === args.projectId) : m.scheduled);
      case "upcoming_tasks": return Promise.resolve(args.projectId ? m.upcoming.filter((u) => u.projectId === args.projectId) : m.upcoming);
      case "get_settings": return Promise.resolve(m.settings);
      case "usage_series": {
        const g = args.granularity;
        return Promise.resolve(g === "year" ? m.yearSeries : g === "month" ? m.monthSeries : m.daySeries);
      }
      case "begin_drain":
      case "cancel_drain": return Promise.resolve(null);
      case "get_session": return Promise.resolve(m.session);
      case "get_session_events": return Promise.resolve(m.sessionEvents);
      case "list_sessions": return Promise.resolve([m.session]);
      case "project_conventions": return Promise.resolve(true);
      case "agent_stats": return Promise.resolve([
        { agent: "claude", sessions: 42, completed: 38, failed: 4, successRate: 0.905, avgCostUsd: 0.31, totalCostUsd: 13.02, avgDurationSecs: 154 },
        { agent: "gemini", sessions: 11, completed: 8, failed: 3, successRate: 0.727, avgCostUsd: 0.12, totalCostUsd: 1.32, avgDurationSecs: 98 },
        { agent: "codex", sessions: 0, completed: 0, failed: 0, successRate: 0, avgCostUsd: 0, totalCostUsd: 0, avgDurationSecs: 0 },
      ]);
      case "project_memory": return Promise.resolve({
        context: "# Project context\n\nA Tauri 2 desktop app orchestrating coding agents.\n\n## File types\n- `.rs` — 24 file(s)\n- `.tsx` — 31 file(s)",
        lessons: "# Lessons\n\n- Always run the test suite before finishing.\n- Keep changes scoped to the task.",
      });
      case "project_git_status": {
        const map = {
          p1: { available: true, branch: "main", dirty: true, ahead: 2, behind: 0, lastCommit: "a1b2c3d", lastSubject: "wire up dashboards" },
          p2: { available: true, branch: "feat/keyboard-nav", dirty: false, ahead: 0, behind: 1, lastCommit: "e4f5a6b", lastSubject: "add shortcuts" },
          p3: { available: true, branch: "main", dirty: false, ahead: 0, behind: 0, lastCommit: "0099aa1", lastSubject: "initial" },
        };
        return Promise.resolve(map[args.id] || { available: false, branch: null, dirty: false, ahead: 0, behind: 0, lastCommit: null, lastSubject: null });
      }
      default:
        // event listen/unlisten and any writes — no-op.
        return Promise.resolve(cmd.startsWith("plugin:event") ? 0 : null);
    }
  },
};
