//! Per-project orchestration conventions.
//!
//! Each managed project may contain an `.orchestrator/` directory whose files
//! steer autonomous behavior. All files are optional — sensible defaults are
//! embedded here and used when a file is absent, so any git repo works out of the
//! box, while power users can override behavior per project.
//!
//! Files:
//! - `config.json` — per-project orchestrator config (currently advisory).
//! - `roadmap.md` — prompt for the roadmap loop (generates new tasks when the
//!   queue empties).
//! - `verify.md` — prompt for the verifier (judges whether a finished task met
//!   its goal).
//! - `task.md` — preamble prepended to every task prompt for this project.

use crate::error::Result;
use std::fs;
use std::path::{Path, PathBuf};

pub const DIR_NAME: &str = ".orchestrator";

pub const DEFAULT_ROADMAP: &str = include_str!("templates/roadmap.md");
pub const DEFAULT_VERIFY: &str = include_str!("templates/verify.md");
pub const DEFAULT_TASK: &str = include_str!("templates/task.md");
pub const DEFAULT_CONFIG: &str = include_str!("templates/config.json");
pub const DEFAULT_README: &str = include_str!("templates/README.md");

/// The `.orchestrator` directory inside a project.
pub fn dir(project_path: impl AsRef<Path>) -> PathBuf {
    project_path.as_ref().join(DIR_NAME)
}

fn read_file(project_path: &Path, name: &str) -> Option<String> {
    fs::read_to_string(dir(project_path).join(name)).ok()
}

/// Roadmap-loop prompt: file contents if present, else the embedded default.
pub fn roadmap_prompt(project_path: impl AsRef<Path>) -> String {
    read_file(project_path.as_ref(), "roadmap.md").unwrap_or_else(|| DEFAULT_ROADMAP.to_string())
}

/// Verification prompt: file contents if present, else the embedded default.
pub fn verify_prompt(project_path: impl AsRef<Path>) -> String {
    read_file(project_path.as_ref(), "verify.md").unwrap_or_else(|| DEFAULT_VERIFY.to_string())
}

/// Optional preamble prepended to every task prompt for a project.
pub fn task_preamble(project_path: impl AsRef<Path>) -> Option<String> {
    read_file(project_path.as_ref(), "task.md")
}

pub const CONTEXT_FILE: &str = "context.md";
pub const LESSONS_FILE: &str = "lessons.md";

/// Auto-generated project context (`context.md`), if present.
pub fn project_context(project_path: impl AsRef<Path>) -> Option<String> {
    read_file(project_path.as_ref(), CONTEXT_FILE)
}

/// Accumulated lessons (`lessons.md`), if present.
pub fn lessons(project_path: impl AsRef<Path>) -> Option<String> {
    read_file(project_path.as_ref(), LESSONS_FILE)
}

/// Read both the context and lessons files for display.
pub fn memory(project_path: impl AsRef<Path>) -> crate::models::ProjectMemory {
    crate::models::ProjectMemory {
        context: project_context(&project_path),
        lessons: lessons(&project_path),
    }
}

/// Append a learned lesson to `lessons.md`, creating the file (and the
/// `.orchestrator` directory) if needed. Lessons are deduplicated by their text
/// so the same feedback isn't recorded repeatedly.
pub fn append_lesson(project_path: impl AsRef<Path>, lesson: &str) -> Result<()> {
    let lesson = lesson.trim();
    if lesson.is_empty() {
        return Ok(());
    }
    let base = dir(&project_path);
    fs::create_dir_all(&base)?;
    let path = base.join(LESSONS_FILE);
    let existing = fs::read_to_string(&path).unwrap_or_default();
    // Skip if this exact lesson line is already recorded.
    if existing
        .lines()
        .any(|l| l.trim_start_matches("- ").trim() == lesson)
    {
        return Ok(());
    }
    let mut out = if existing.is_empty() {
        String::from("# Lessons\n\nDurable insights learned from prior task reviews. These are\nincluded in every task prompt for this project.\n\n")
    } else {
        existing
    };
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str("- ");
    // Collapse newlines so each lesson is a single bullet.
    out.push_str(&lesson.split_whitespace().collect::<Vec<_>>().join(" "));
    out.push('\n');
    fs::write(&path, out)?;
    Ok(())
}

/// Write (overwrite) the auto-generated `context.md`.
pub fn write_context(project_path: impl AsRef<Path>, content: &str) -> Result<()> {
    let base = dir(&project_path);
    fs::create_dir_all(&base)?;
    fs::write(base.join(CONTEXT_FILE), content)?;
    Ok(())
}

/// Deterministically build a project-context document by inspecting the repo:
/// the project name, the README's opening lines, the top-level entries, and a
/// language breakdown by source-file extension. Cheap, offline, no agent call.
pub fn generate_context(project_path: impl AsRef<Path>) -> Result<String> {
    let root = project_path.as_ref();
    let name = root
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "project".into());
    let mut out = format!("# Project context: {name}\n\n");
    out.push_str("_Auto-generated by Claude Orchestrator. Edit freely — it is\nincluded in every task prompt for this project._\n\n");

    // README excerpt.
    let readme = ["README.md", "README", "readme.md"]
        .iter()
        .find_map(|f| fs::read_to_string(root.join(f)).ok());
    if let Some(text) = readme {
        let excerpt: Vec<&str> = text.lines().take(30).collect();
        out.push_str("## README (excerpt)\n\n");
        out.push_str(&excerpt.join("\n"));
        out.push_str("\n\n");
    }

    // Top-level entries.
    if let Ok(entries) = fs::read_dir(root) {
        let mut names: Vec<String> = entries
            .flatten()
            .filter_map(|e| {
                let n = e.file_name().to_string_lossy().to_string();
                if n.starts_with('.') {
                    None
                } else {
                    Some(n)
                }
            })
            .collect();
        names.sort();
        if !names.is_empty() {
            out.push_str("## Top-level layout\n\n");
            for n in names.iter().take(40) {
                out.push_str(&format!("- {n}\n"));
            }
            out.push('\n');
        }
    }

    // Language breakdown by extension (bounded, shallow walk).
    let mut counts: std::collections::BTreeMap<String, u32> = std::collections::BTreeMap::new();
    count_extensions(root, 0, &mut counts);
    if !counts.is_empty() {
        let mut ranked: Vec<(String, u32)> = counts.into_iter().collect();
        ranked.sort_by_key(|b| std::cmp::Reverse(b.1));
        out.push_str("## File types\n\n");
        for (ext, n) in ranked.into_iter().take(12) {
            out.push_str(&format!("- `.{ext}` — {n} file(s)\n"));
        }
        out.push('\n');
    }
    Ok(out)
}

/// Tally source-file extensions up to a shallow depth, skipping common vendor
/// and VCS directories so the walk stays cheap.
fn count_extensions(
    dir_path: &Path,
    depth: u32,
    counts: &mut std::collections::BTreeMap<String, u32>,
) {
    if depth > 3 {
        return;
    }
    let Ok(entries) = fs::read_dir(dir_path) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.')
            || matches!(
                name.as_str(),
                "node_modules" | "target" | "dist" | "build" | "vendor" | "venv" | "__pycache__"
            )
        {
            continue;
        }
        if path.is_dir() {
            count_extensions(&path, depth + 1, counts);
        } else if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
            *counts.entry(ext.to_lowercase()).or_insert(0) += 1;
        }
    }
}

/// True if the project already has an `.orchestrator` directory.
pub fn is_initialized(project_path: impl AsRef<Path>) -> bool {
    dir(project_path).is_dir()
}

/// Write the default convention files into a project, without overwriting any
/// that already exist. Returns the list of files created (relative paths).
pub fn scaffold(project_path: impl AsRef<Path>) -> Result<Vec<String>> {
    let base = dir(&project_path);
    fs::create_dir_all(&base)?;
    let files = [
        ("README.md", DEFAULT_README),
        ("config.json", DEFAULT_CONFIG),
        ("roadmap.md", DEFAULT_ROADMAP),
        ("verify.md", DEFAULT_VERIFY),
        ("task.md", DEFAULT_TASK),
    ];
    let mut created = Vec::new();
    for (name, contents) in files {
        let path = base.join(name);
        if !path.exists() {
            fs::write(&path, contents)?;
            created.push(format!("{DIR_NAME}/{name}"));
        }
    }
    Ok(created)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_used_when_missing() {
        let dir = std::env::temp_dir().join(format!("orch-conv-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        assert!(!is_initialized(&dir));
        assert_eq!(roadmap_prompt(&dir), DEFAULT_ROADMAP);
        assert!(task_preamble(&dir).is_none());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn lessons_append_and_dedupe() {
        let dir = std::env::temp_dir().join(format!("orch-lesson-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        assert!(lessons(&dir).is_none());
        append_lesson(&dir, "Always run the test suite before finishing.").unwrap();
        append_lesson(&dir, "Always run the test suite before finishing.").unwrap();
        append_lesson(&dir, "Keep changes scoped.").unwrap();
        let body = lessons(&dir).unwrap();
        // Each distinct lesson appears exactly once.
        assert_eq!(body.matches("Always run the test suite").count(), 1);
        assert!(body.contains("Keep changes scoped."));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn generate_context_summarizes_repo() {
        let dir = std::env::temp_dir().join(format!("orch-ctx-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("README.md"), "# Cool Project\n\nDoes things.").unwrap();
        std::fs::write(dir.join("main.rs"), "fn main() {}").unwrap();
        let ctx = generate_context(&dir).unwrap();
        assert!(ctx.contains("Cool Project"));
        assert!(ctx.contains("README"));
        assert!(ctx.contains("`.rs`"));
        // Round-trips through write/read.
        write_context(&dir, &ctx).unwrap();
        assert_eq!(project_context(&dir).as_deref(), Some(ctx.as_str()));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn scaffold_creates_then_preserves() {
        let dir = std::env::temp_dir().join(format!("orch-conv-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        let created = scaffold(&dir).unwrap();
        assert!(created.iter().any(|f| f.ends_with("roadmap.md")));
        assert!(is_initialized(&dir));
        // Override a file, re-scaffold, ensure it is not clobbered.
        let roadmap = super::dir(&dir).join("roadmap.md");
        std::fs::write(&roadmap, "custom").unwrap();
        let created2 = scaffold(&dir).unwrap();
        assert!(created2.is_empty());
        assert_eq!(std::fs::read_to_string(&roadmap).unwrap(), "custom");
        std::fs::remove_dir_all(&dir).ok();
    }
}
